name: Workflow lors d'un push
on: push
jobs:
  mon_job:
    name: Build, test et run application
    runs-on: ubuntu-latest
    steps:
      - name: Récupération de notre application
        uses: actions/checkout@v4
      - name: Installation des dépendances
        run: echo "Installation des dépendances"
      #      - name: Installation des dépendances
      #        run: mvn dependency:go-offline
      - name: Build de l'application
        run: echo "Build de l'application"
#      - name: Build de l'application
#        run: mvn spring-boot:run
#      - name: Test de l'application
#        run: mvn test
